import os
import json
import sqlite3
from datetime import datetime
from zoneinfo import ZoneInfo

IST = ZoneInfo("Asia/Kolkata")

ROOT = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

DB_PATH = os.path.join(
    ROOT,
    "data",
    "hospital.db"
)


# ============================================================
# DATABASE CONNECTION (same pattern as lab_report_tools.py)
# ============================================================

def get_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# ============================================================
# CONTEXT GATHERING
# ============================================================
#
# Everything here is a straight read of data that already exists in
# the app (cases table from the Symptom Checker, lab_reports/lab_values
# from the Lab Report Explainer). No new tables, no new writes.

def get_recent_cases(patient_name, limit=5):
    """Last N symptom-checker cases for this patient, most recent first."""
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT symptoms, severity, department, summary, recommendation, created_at
            FROM cases
            WHERE LOWER(patient_name) = LOWER(?)
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (patient_name, limit),
        )
        return [dict(row) for row in cursor.fetchall()]


def get_recent_lab_reports(patient_name, limit=3):
    """Last N lab reports for this patient (metadata + summary), most recent first."""
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT id, file_name, ai_summary, created_at
            FROM lab_reports
            WHERE LOWER(patient_name) = LOWER(?)
            ORDER BY created_at DESC
            LIMIT ?
            """,
            (patient_name, limit),
        )
        return [dict(row) for row in cursor.fetchall()]


def get_lab_values_for_reports(report_ids):
    """All extracted parameter rows for a set of report ids, in one query."""
    if not report_ids:
        return {}

    placeholders = ",".join("?" for _ in report_ids)
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            f"""
            SELECT report_id, parameter, value, unit, ref_low, ref_high, flag
            FROM lab_values
            WHERE report_id IN ({placeholders})
            ORDER BY parameter
            """,
            tuple(report_ids),
        )
        rows = [dict(row) for row in cursor.fetchall()]

    grouped = {}
    for row in rows:
        grouped.setdefault(row["report_id"], []).append(row)
    return grouped


def has_any_history(patient_name):
    """Quick check used to decide whether prep generation is even possible."""
    return bool(get_recent_cases(patient_name, limit=1)) or bool(
        get_recent_lab_reports(patient_name, limit=1)
    )


def get_all_patients_with_history():
    """Distinct patient names appearing in EITHER the cases table or the
    lab_reports table, so the prep tab's dropdown covers anyone with any
    relevant history - not just people who've used the Lab Reports tab."""
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT DISTINCT patient_name FROM cases
            UNION
            SELECT DISTINCT patient_name FROM lab_reports
            ORDER BY patient_name COLLATE NOCASE
            """
        )
        return [row["patient_name"] for row in cursor.fetchall()]


# ============================================================
# LLM PREP GENERATION
# ============================================================
#
# Design choice: the "reports to bring" checklist is built directly from
# get_recent_lab_reports() above, NOT generated by the LLM - the app
# already has the exact file names and dates, so there's no reason to
# let the model invent or misremember them. The LLM is only asked for
# the two things that actually require reasoning: the doctor-visit
# questions, and a plain-English summary of what's changed.

PREP_SYSTEM_PROMPT = """You are a pre-appointment assistant helping a patient prepare for a doctor's visit.
You will receive: the reason for today's visit, the doctor's specialty (if given), a set of recent
symptom-checker case summaries, and recent lab report summaries with flagged values.

Using only the information given, produce:
1. 5 to 7 specific questions the patient should ask their doctor. Base these on the actual data provided
   - reference specific values, symptoms, or trends where relevant - not generic questions.
2. A short (2-4 sentence) plain-English summary of what has changed or is notable since the last visit.

Respond with ONLY valid JSON (no markdown fences, no commentary) in exactly this shape:

{{
  "questions": ["...", "..."],
  "change_summary": "..."
}}

Rules:
- Never suggest starting, stopping, or changing any medication or dosage.
- Never state or imply a diagnosis. Frame everything as questions to raise or things to mention,
  not conclusions.
- If the provided history is thin (e.g. only one case or one lab report), say so plainly in the
  change_summary rather than inventing a trend.
- Do not fabricate any symptom, value, or date that isn't in the context you were given.
- The lab data is pre-sorted into "OUT-OF-RANGE VALUES", "NORMAL VALUES", and "UNCLASSIFIED"
  for you. Only raise questions about parameters listed under OUT-OF-RANGE VALUES. Never describe
  a parameter listed under NORMAL VALUES as low, high, abnormal, or a concern, even if it appears
  in the same report or the same body system as an out-of-range value (e.g. do not call RBC count
  a concern just because haemoglobin in the same report is out of range - only flag RBC count
  itself if it appears in the OUT-OF-RANGE list).
"""


def generate_appointment_prep(
    patient_name,
    visit_reason,
    doctor_specialty,
    recent_cases,
    recent_lab_reports,
    lab_values_by_report,
    llm,
):
    """
    llm: a LangChain-compatible chat model, passed in from app.py (same
    convention as parse_lab_report_with_llm in lab_report_tools.py).
    Returns {"questions": [str, ...], "change_summary": str, "reports_to_bring": [dict, ...]}.
    """
    from langchain.prompts import ChatPromptTemplate
    from langchain.schema.output_parser import StrOutputParser

    context_parts = [f"Patient: {patient_name}"]
    context_parts.append(f"Reason for visit: {visit_reason or 'Not specified'}")
    context_parts.append(f"Doctor's specialty: {doctor_specialty or 'Not specified'}")

    # Tracked separately from the context text so we can enforce this in code
    # afterwards, rather than only hoping the model honors it. Two rounds of
    # prompt tightening still let the model call a NORMAL-flagged parameter
    # "low" when it appeared alongside a genuinely out-of-range one (e.g.
    # RBC count called "low" just because hemoglobin in the same report was
    # low) - the model pattern-matches to familiar clinical combinations
    # (anemia = low hemoglobin + low RBC) even when told not to. A deterministic
    # filter below is the reliable fix; the prompt instructions are kept too
    # since they still reduce how often this needs to trigger.
    normal_parameter_names = set()

    if recent_cases:
        context_parts.append("\nRecent symptom-checker cases (most recent first):")
        for c in recent_cases:
            context_parts.append(
                f"- [{c['created_at']}] Severity: {c['severity']}, Dept: {c['department']}\n"
                f"  Symptoms: {c['symptoms']}\n"
                f"  Summary: {c['summary']}\n"
                f"  Recommendation: {c['recommendation']}"
            )
    else:
        context_parts.append("\nNo past symptom-checker cases on file for this patient.")

    if recent_lab_reports:
        context_parts.append("\nRecent lab reports (most recent first):")
        for r in recent_lab_reports:
            context_parts.append(f"- [{r['created_at']}] {r['file_name']}")
            context_parts.append(f"  AI summary: {r['ai_summary']}")

            values = lab_values_by_report.get(r["id"], [])
            abnormal_values = [v for v in values if v["flag"] in ("low", "high", "critical")]
            normal_values = [v for v in values if v["flag"] == "normal"]
            unknown_values = [v for v in values if v["flag"] not in ("low", "high", "critical", "normal")]

            for v in normal_values:
                normal_parameter_names.add(v["parameter"].strip().lower())

            if abnormal_values:
                context_parts.append("  OUT-OF-RANGE VALUES (safe to raise as a question about):")
                for v in abnormal_values:
                    ref = (
                        f"{v['ref_low']}-{v['ref_high']}"
                        if v["ref_low"] is not None and v["ref_high"] is not None
                        else "unknown"
                    )
                    context_parts.append(
                        f"    - {v['parameter']}: {v['value']} {v['unit']} is {v['flag'].upper()} "
                        f"(reference range: {ref})"
                    )

            if normal_values:
                normal_list = ", ".join(v["parameter"] for v in normal_values)
                context_parts.append(
                    f"  NORMAL VALUES (do NOT describe these as low/high/abnormal/a concern): {normal_list}"
                )

            if unknown_values:
                unknown_list = ", ".join(v["parameter"] for v in unknown_values)
                context_parts.append(
                    f"  UNCLASSIFIED (no reference range available - do not guess whether these "
                    f"are normal or abnormal): {unknown_list}"
                )
    else:
        context_parts.append("\nNo past lab reports on file for this patient.")

    context_text = "\n".join(context_parts)

    prompt = ChatPromptTemplate.from_messages([
        ("system", PREP_SYSTEM_PROMPT),
        ("human", "{context}"),
    ])

    chain = prompt | llm | StrOutputParser()
    output = chain.invoke({"context": context_text})

    cleaned = output.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.lower().startswith("json"):
            cleaned = cleaned[4:]
        cleaned = cleaned.strip()

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        parsed = {
            "questions": [],
            "change_summary": (
                "The AI could not produce a structured summary this time. "
                "Please try generating again."
            ),
        }

    questions = parsed.get("questions", [])
    if not isinstance(questions, list):
        questions = []
    questions = [str(q).strip() for q in questions if str(q).strip()]

    # Deterministic guardrail: drop any question that mentions a parameter
    # name we know is flagged NORMAL, since the model has repeatedly ignored
    # prompt instructions telling it not to characterize normal values as a
    # concern. Whole-question removal (not editing/rewriting) so we never
    # risk leaving a mangled half-correct sentence on screen.
    safe_questions = []
    for q in questions:
        q_lower = q.lower()
        if any(name in q_lower for name in normal_parameter_names if name):
            continue
        safe_questions.append(q)
    questions = safe_questions

    reports_to_bring = [
        {"file_name": r["file_name"], "date": r["created_at"]}
        for r in recent_lab_reports
    ]

    return {
        "questions": questions,
        "change_summary": str(parsed.get("change_summary", "")).strip(),
        "reports_to_bring": reports_to_bring,
    }